### PR TITLE
v2.1.1 Normalize

### PR DESCRIPTION
**Pull request by f3rno**
## Normalize

This PR is part of a series covering all `bfx-api-*` and `bfx-hf-*` repos to standardize their structure and improve Github productivity.

### Requires
* [x] merge & publish https://github.com/bitfinexcom/bfx-hf-models-adapter-sql/pull/3
* [x] merge & publish https://github.com/bitfinexcom/bfx-hf-models-adapter-lowdb/pull/4
* [x] merge & publish https://github.com/bitfinexcom/bfx-hf-ext-plugin-bitfinex/pull/3

### Merge TODO
* [x] audit Github issues (create where necessary)
* [x] self review

### Extracted Issues
* https://github.com/bitfinexcom/bfx-hf-models/issues/7

### Normalization TODO
* [x] manifest: bump version to X
* [x] manifest: ensure `author` field set to `Bitfinex`
* [x] manifest: audit contributors array
* [x] manifest: bump deps
* [x] changelog: create or update
* [x] ensure example exists
* [x] readme: audit/update
* [x] convert code TODOs to issues
* [x] add travis lint/unit file
* [x] add Issue/PR template
* [x] ensure `npm test` exists and runs
* [x] standard --fix
* [x] ensure eslint config exists

### CODE REVIEW

**Comment by JacobPlaster** [comment]
Are all of the tests failing or are they just irrelevant?

**Comment by JacobPlaster** [comment]
I was hoping that we could start adding more test coverage the to public libs in the future so it would be best to salvage what we can

**Comment by f3rno** [comment]
The tests became irrelevant after a past refactor, they were all failing since the methods no longer exist. I created an issue to add new tests, and will do so in the future (another upcoming project, hehe)

**Comment by JacobPlaster** [comment]
Ok could you add that to Asana so we dont lose track of it?

**Review by JacobPlaster — APPROVED** [review]

**Pull request merged**
